#!/usr/bin/env bash

usage() {

printf "%s" "\
usage: $(basename "$0") --image-dir <image_dir> [options]

Options:
    -h, --help                  show this help message and exit.
    -i, --image-dir <image_dir> directory where images are stored (required).
    -r, --remove-image          remove image file after posting.
    -u, --user <user>           twitter username (if not provided, twurl default will be used).

"

exit 1

}

get_args() {

    TEMP=$(getopt \
        -l 'image-dir:,user:,help,remove-image' \
        -o 'i:u:hr' \
        -n "$(basename "$0")" \
        -- "$@") || exit 1

    eval set -- "$TEMP"
    unset TEMP

    while true; do
        case "$1" in
            '-i' | '--image-dir')
                image_dir="$2"
                shift 2
                continue
            ;;
            '-u' | '--user')
                user="$2"
                shift 2
                continue
            ;;
            '-h' | '--help')
                usage
            ;;
            '-r' | '--remove-image')
                remove_image=1
                shift
                continue
            ;;
            '--')
                shift
                break
            ;;
            *)
                printf 'error' >&2
                exit 1
            ;;
        esac
    done

}

check_args() {

    [[ "$image_dir" ]] || usage

}

upload_img() {

    if ! twurl accounts &>/dev/null; then
        echo "error: twurl has no registered accounts" >&2
        exit 1
    fi

    exit 0

    [[ "$user" ]] && user="-u$user"

    frame="$(find "$image_dir" -type f | shuf -n 1)"
    media_id="$(twurl "$user" -X POST -H upload.twitter.com \
        "/1.1/media/upload.json?media_category=TWEET_IMAGE" -f "$frame" -F media | \
        jshon -e media_id)"

    twurl "$user" -d "media_ids=$media_id" "/1.1/statuses/update.json" > /dev/null

    [[ "$remove_image" ]] && rm -f "$frame"

}

main() {

    get_args "$@"
    check_args
    upload_img

    return 0

}

main "$@"
